### ISSUE TITLE
使用nb orm upgrade更新迁移数据库异常

### ISSUE THREAD

**Issue by ABKQPO** [nonebot/plugin-orm#10]
```
Traceback (most recent call last):
  File "<string>", line 33, in <module>
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot_plugin_orm\__main__.py", line 281, in main
    orm(*args, **kwargs)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\NoneBot\ABK\.venv\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot_plugin_orm\__main__.py", line 86, in wrapper
    return f(ctx.obj, *args, **kwargs)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot_plugin_orm\__main__.py", line 173, in upgrade
    return migrate.upgrade(*args, **kwargs)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot_plugin_orm\migrate.py", line 627, in upgrade
    script.run_env()
  File "D:\NoneBot\ABK\.venv\lib\site-packages\alembic\script\base.py", line 585, in run_env
    util.load_python_file(self.dir, "env.py")
  File "D:\NoneBot\ABK\.venv\lib\site-packages\alembic\util\pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\alembic\util\pyfiles.py", line 109, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot_plugin_orm\templates\generic\env.py", line 84, in <module>
    await_fallback(run_migrations_online())
  File "D:\NoneBot\ABK\.venv\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 141, in await_fallback
    loop = get_event_loop()
  File "D:\NoneBot\ABK\.venv\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 260, in get_event_loop
    return asyncio.get_event_loop_policy().get_event_loop()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 656, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'MainThread'.
```

**Comment by ProgramRipper** [comment]
我没有复现出问题, 但是仍然在 [v0.6.3](https://github.com/nonebot/plugin-orm/releases/tag/v0.6.3) 中尝试修复了一下, 可以验证一下修复是否有效. 如果问题仍然存在, 欢迎 reopen issue.

**Comment by shinyashen** [comment]
最近初始安装此插件后控制台提示`click.exceptions.UsageError: 目标数据库未更新到最新迁移. 请通过 nb orm upgrade 升级数据库后重试.`尝试使用`nb orm upgrade`更新迁移数据库后同样出现异常，日志如下（python版本为3.12.3）：
```
Traceback (most recent call last):
  File "<string>", line 37, in <module>
  File "/home/mua/.conda/envs/MUAnonebot2/lib/python3.12/site-packages/nonebot_plugin_orm/__main__.py", line 283, in main
    orm(*args, **kwargs)
  File "/home/mua/.local/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mua/.local/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/mua/.local/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mua/.local/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mua/.local/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mua/.local/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mua/.conda/envs/MUAnonebot2/lib/python3.12/site-packages/nonebot_plugin_orm/__main__.py", line 86, in wrapper
    return f(ctx.obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mua/.conda/envs/MUAnonebot2/lib/python3.12/site-packages/nonebot_plugin_orm/__main__.py", line 175, in upgrade
    return migrate.upgrade(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mua/.conda/envs/MUAnonebot2/lib/python3.12/site-packages/nonebot_plugin_orm/migrate.py", line 635, in upgrade
    script.run_env()
  File "/home/mua/.conda/envs/MUAnonebot2/lib/python3.12/site-packages/alembic/script/base.py", line 583, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/home/mua/.conda/envs/MUAnonebot2/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mua/.conda/envs/MUAnonebot2/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/mua/.conda/envs/MUAnonebot2/lib/python3.12/site-packages/nonebot_plugin_orm/templates/generic/env.py", line 88, in <module>
    asyncio.run(coro)
  File "/home/mua/.conda/envs/MUAnonebot2/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/mua/.conda/envs/MUAnonebot2/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mua/.conda/envs/MUAnonebot2/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/mua/.conda/envs/MUAnonebot2/lib/python3.12/site-packages/nonebot_plugin_orm/templates/generic/env.py", line 79, in run_migrations_online
    await connection.run_sync(do_run_migrations)
  File "/home/mua/.conda/envs/MUAnonebot2/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/engine.py", line 886, in run_sync
    return await greenlet_spawn(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mua/.conda/envs/MUAnonebot2/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 203, in greenlet_spawn
    result = context.switch(value)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mua/.conda/envs/MUAnonebot2/lib/python3.12/site-packages/nonebot_plugin_orm/templates/generic/env.py", line 69, in do_run_migrations
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/home/mua/.conda/envs/MUAnonebot2/lib/python3.12/site-packages/alembic/runtime/environment.py", line 948, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/home/mua/.conda/envs/MUAnonebot2/lib/python3.12/site-packages/alembic/runtime/migration.py", line 627, in run_migrations
    step.migration_fn(**kw)
TypeError: upgrade() missing 1 required positional argument: 'name'
