### ISSUE TITLE
Bug: 使用 `Python 3.10` 时，如果 `handle` 函数参数里有 `pydantic.BaseModel` 类型的参数，启动会报错

### ISSUE THREAD

**Issue by shoucandanghehe** [nonebot/plugin-orm#15]
我知道这很抽象，但是我确实触发了
最简单复现👇
```python3
from nonebot import on, require
from pydantic import BaseModel

require('nonebot_plugin_orm')


test = on()


@test.handle()
async def _(foo: BaseModel): ...
```
<details>
<summary>log</summary>

```
05-05 08:36:24 [ERROR] nonebot | Failed to import "test_plugin"
Traceback (most recent call last):
  File "/home/scdhh/code/nonebot-plugin-tetris-stats/bot.py", line 10, in <module>
    nonebot.load_from_toml('pyproject.toml')
  File "/venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 131, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 65, in load_all_plugins
    return manager.load_all_plugins()
  File "/venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 203, in load_all_plugins
    return set(
  File "/venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 204, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 167, in load_plugin
    module = importlib.import_module(self._third_party_plugin_ids[name])
  File "/home/scdhh/miniconda3/envs/python3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 255, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/scdhh/code/nonebot-plugin-tetris-stats/test_plugin.py", line 11, in <module>
    async def _(foo: BaseModel): ...
  File "/venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 452, in _decorator
    cls.append_handler(func, parameterless=parameterless)
  File "/venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 433, in append_handler
    handler_ = Dependent[Any].parse(
  File "/venv/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 157, in parse
    params = cls.parse_params(call, allow_types)
  File "/venv/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 113, in parse_params
    if field_info := allow_type._check_param(param, allow_types):
  File "/venv/lib/python3.10/site-packages/nonebot_plugin_orm/param.py", line 152, in _check_param
    if models := generic_issubclass(pattern, type_annotation):
  File "/venv/lib/python3.10/site-packages/nonebot_plugin_orm/utils.py", line 151, in generic_issubclass
    return issubclass(scls, cls)
  File "/home/scdhh/miniconda3/envs/python3.10/lib/python3.10/abc.py", line 123, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
TypeError: issubclass() arg 1 must be a class
```

</details>

<details>

<summary>如果不加载 orm NoneBot 也会报错</summary>

```
05-05 08:12:27 [ERROR] nonebot | Failed to import "test_plugin"
Traceback (most recent call last):
  File "/home/scdhh/code/nonebot-plugin-tetris-stats/bot.py", line 10, in <module>
    nonebot.load_from_toml('pyproject.toml')
  File "/venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 131, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 65, in load_all_plugins
    return manager.load_all_plugins()
  File "/venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 203, in load_all_plugins
    return set(
  File "/venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 204, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 167, in load_plugin
    module = importlib.import_module(self._third_party_plugin_ids[name])
  File "/home/scdhh/miniconda3/envs/python3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 255, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/scdhh/code/nonebot-plugin-tetris-stats/test_plugin.py", line 11, in <module>
    async def _(foo: BaseModel): ...
  File "/venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 452, in _decorator
    cls.append_handler(func, parameterless=parameterless)
  File "/venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 433, in append_handler
    handler_ = Dependent[Any].parse(
  File "/venv/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 157, in parse
    params = cls.parse_params(call, allow_types)
  File "/venv/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 116, in parse_params
    raise ValueError(
ValueError: Unknown parameter foo for function <function _ at 0x7f350afef490> with type <class 'pydantic.main.BaseModel'>
```
</details>

***

但是别急 我们还有 `Alconna`，在 `Alconna` 里这用法大概不奇怪）
(其中的 `CustomModel` 和 `foo` 都是不必要的，但是为了方便理解用法所以加了)
```python3
from arclet.alconna import Alconna, Arg
from nonebot import require
from pydantic import BaseModel

require('nonebot_plugin_alconna')

from nonebot_plugin_alconna import on_alconna  # noqa: E402


class CustomModel(BaseModel):
    string: str


def foo(bar: str) -> CustomModel:
    # maybe do something
    return CustomModel(string=bar)


alc = on_alconna(Alconna('test', Arg('foo', foo)))


@alc.assign('foo')
async def _(foo: CustomModel): ...
```
```05-05 08:14:10 [SUCCESS] nonebot | Succeeded to load plugin "test_plugin"```
***
但是如果再加上 `orm`
<details>
<summary>log</summary>

```
05-05 08:18:06 [ERROR] nonebot | Failed to import "test_plugin"
Traceback (most recent call last):
  File "/home/scdhh/code/nonebot-plugin-tetris-stats/bot.py", line 10, in <module>
    nonebot.load_from_toml('pyproject.toml')
  File "/venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 131, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 65, in load_all_plugins
    return manager.load_all_plugins()
  File "/venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 203, in load_all_plugins
    return set(
  File "/venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 204, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 167, in load_plugin
    module = importlib.import_module(self._third_party_plugin_ids[name])
  File "/home/scdhh/miniconda3/envs/python3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 255, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/scdhh/code/nonebot-plugin-tetris-stats/test_plugin.py", line 22, in <module>
    async def _(foo: CustomModel): ...
  File "/venv/lib/python3.10/site-packages/nonebot_plugin_alconna/matcher.py", line 353, in _decorator
    cls.append_handler(func, parameterless=parameterless)
  File "/venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 433, in append_handler
    handler_ = Dependent[Any].parse(
  File "/venv/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 157, in parse
    params = cls.parse_params(call, allow_types)
  File "/venv/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 113, in parse_params
    if field_info := allow_type._check_param(param, allow_types):
  File "/venv/lib/python3.10/site-packages/nonebot_plugin_orm/param.py", line 152, in _check_param
    if models := generic_issubclass(pattern, type_annotation):
  File "/venv/lib/python3.10/site-packages/nonebot_plugin_orm/utils.py", line 151, in generic_issubclass
    return issubclass(scls, cls)
  File "/home/scdhh/miniconda3/envs/python3.10/lib/python3.10/abc.py", line 123, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
TypeError: issubclass() arg 1 must be a class
```
</details>

**Boom💥**

**Comment by ProgramRipper** [comment]
fix in ad3c8659ce9d87fe023b33a985860e832c11058b
