### ISSUE TITLE
【求助】[ERROR] nonebot | Failed to import "nonebot_plugin_session_orm"

### ISSUE THREAD

**Issue by freght** [nonebot/plugin-orm#18]
```
08-19 19:51:36 [ERROR] nonebot | Failed to import "nonebot_plugin_session_orm"
Traceback (most recent call last):
  File "D:\qqbot\anobot\atri\bot.py", line 11, in <module>
    nonebot.load_plugin("nonebot_plugin_memes")
  File "D:\qqbot\anobot\atri\.venv\Lib\site-packages\nonebot\plugin\load.py", line 40, in load_plugin
    return manager.load_plugin(module_path)
  File "D:\qqbot\anobot\atri\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 167, in load_plugin
    module = importlib.import_module(self._third_party_plugin_ids[name])
  File "D:\Python3.12\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "D:\qqbot\anobot\atri\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 255, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\qqbot\anobot\atri\.venv\Lib\site-packages\nonebot_plugin_memes\__init__.py", line 9, in <module>
    require("nonebot_plugin_session_orm")
  File "D:\qqbot\anobot\atri\.venv\Lib\site-packages\nonebot\plugin\load.py", line 185, in require
    plugin = load_plugin(name)
  File "D:\qqbot\anobot\atri\.venv\Lib\site-packages\nonebot\plugin\load.py", line 40, in load_plugin
    return manager.load_plugin(module_path)
> File "D:\qqbot\anobot\atri\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 167, in load_plugin
    module = importlib.import_module(self._third_party_plugin_ids[name])
  File "D:\Python3.12\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "D:\qqbot\anobot\atri\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 255, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\qqbot\anobot\atri\.venv\Lib\site-packages\nonebot_plugin_session_orm\__init__.py", line 7, in <module>
    from . import migrations
ImportError: cannot import name 'migrations' from partially initialized module 'nonebot_plugin_session_orm' (most likely due to a circular import) (D:\qqbot\anobot\atri\.venv\Lib\site-packages\nonebot_plugin_session_orm\__init__.py)
08-19 19:51:36 [ERROR] nonebot | Failed to import "nonebot_plugin_memes"
Traceback (most recent call last):
  File "D:\qqbot\anobot\atri\bot.py", line 11, in <module>
    nonebot.load_plugin("nonebot_plugin_memes")
  File "D:\qqbot\anobot\atri\.venv\Lib\site-packages\nonebot\plugin\load.py", line 40, in load_plugin
    return manager.load_plugin(module_path)
> File "D:\qqbot\anobot\atri\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 167, in load_plugin
    module = importlib.import_module(self._third_party_plugin_ids[name])
  File "D:\Python3.12\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "D:\qqbot\anobot\atri\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 255, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\qqbot\anobot\atri\.venv\Lib\site-packages\nonebot_plugin_memes\__init__.py", line 9, in <module>
    require("nonebot_plugin_session_orm")
  File "D:\qqbot\anobot\atri\.venv\Lib\site-packages\nonebot\plugin\load.py", line 188, in require
    raise RuntimeError(f'Cannot load plugin "{name}"!')
RuntimeError: Cannot load plugin "nonebot_plugin_session_orm"!
Traceback (most recent call last):
  File "D:\qqbot\anobot\atri\bot.py", line 12, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "D:\qqbot\anobot\atri\.venv\Lib\site-packages\nonebot\plugin\load.py", line 131, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\qqbot\anobot\atri\.venv\Lib\site-packages\nonebot\plugin\load.py", line 63, in load_all_plugins
    manager = PluginManager(module_path, plugin_dir)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\qqbot\anobot\atri\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 54, in __init__
    self._prepare_plugins()
  File "D:\qqbot\anobot\atri\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 116, in _prepare_plugins
    raise RuntimeError(
RuntimeError: Plugin already exists: nonebot_plugin_memes! Check your plugin name
```

安装插件nonebot-plugin-memes启动之后就这样报错，执行了pip install nonebot-plugin-session-orm
也没有解决问题，请问有什么解决方法啊

**Comment by ProgramRipper** [comment]
请在对应的仓库中发起 issue 哦。
cc @MeetWq
https://github.com/noneplugin/nonebot-plugin-session-orm/blob/18673cc63db75b7e4a6cb65849d5bb145f3f4557/nonebot_plugin_session_orm/__init__.py#L19
