### ISSUE TITLE
Bug: `pydantic==2.9.0` 时插件加载出错

### ISSUE THREAD

**Issue by MeetWq** [nonebot/plugin-orm#19]
报错如下：
```
09-07 14:17:22 [ERROR] nonebot | Failed to import "nonebot_plugin_orm"
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "F:\Temp\bot\testbot\.venv\lib\site-packages\nonebot\plugin\load.py", line 131, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "F:\Temp\bot\testbot\.venv\lib\site-packages\nonebot\plugin\load.py", line 65, in load_all_plugins
    return manager.load_all_plugins()
  File "F:\Temp\bot\testbot\.venv\lib\site-packages\nonebot\plugin\manager.py", line 203, in load_all_plugins
    return set(
  File "F:\Temp\bot\testbot\.venv\lib\site-packages\nonebot\plugin\manager.py", line 204, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
  File "F:\Temp\bot\testbot\.venv\lib\site-packages\nonebot\plugin\manager.py", line 169, in load_plugin
    module = importlib.import_module(self._searched_plugin_ids[name])
  File "C:\Users\wangqian\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "F:\Temp\bot\testbot\.venv\lib\site-packages\nonebot\plugin\manager.py", line 255, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\Temp\bot\testbot\src\plugins\test\__init__.py", line 3, in <module>
    require("nonebot_plugin_orm")
  File "F:\Temp\bot\testbot\.venv\lib\site-packages\nonebot\plugin\load.py", line 185, in require
    plugin = load_plugin(name)
  File "F:\Temp\bot\testbot\.venv\lib\site-packages\nonebot\plugin\load.py", line 40, in load_plugin
    return manager.load_plugin(module_path)
> File "F:\Temp\bot\testbot\.venv\lib\site-packages\nonebot\plugin\manager.py", line 167, in load_plugin
    module = importlib.import_module(self._third_party_plugin_ids[name])
  File "C:\Users\wangqian\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "F:\Temp\bot\testbot\.venv\lib\site-packages\nonebot\plugin\manager.py", line 255, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\Temp\bot\testbot\.venv\lib\site-packages\nonebot_plugin_orm\__init__.py", line 25, in <module>
    from .config import Config, plugin_config
  File "F:\Temp\bot\testbot\.venv\lib\site-packages\nonebot_plugin_orm\config.py", line 37, in <module>
    plugin_config = get_plugin_config(Config)
  File "F:\Temp\bot\testbot\.venv\lib\site-packages\nonebot\plugin\__init__.py", line 173, in get_plugin_config
    return type_validate_python(config, model_dump(get_driver().config))
  File "F:\Temp\bot\testbot\.venv\lib\site-packages\nonebot\compat.py", line 225, in type_validate_python
    return TypeAdapter(type_).validate_python(data)
  File "F:\Temp\bot\testbot\.venv\lib\site-packages\pydantic\type_adapter.py", line 144, in wrapped
    return func(self, *args, **kwargs)
  File "F:\Temp\bot\testbot\.venv\lib\site-packages\pydantic\type_adapter.py", line 375, in validate_python
    return self.validator.validate_python(object, strict=strict, from_attributes=from_attributes, context=context)
  File "C:\Users\wangqian\AppData\Local\Programs\Python\Python310\lib\functools.py", line 981, in __get__
    val = self.func(instance)
  File "F:\Temp\bot\testbot\.venv\lib\site-packages\pydantic\type_adapter.py", line 144, in wrapped
    return func(self, *args, **kwargs)
  File "F:\Temp\bot\testbot\.venv\lib\site-packages\pydantic\type_adapter.py", line 319, in validator
    self._init_core_attrs(rebuild_mocks=True)  # Do not expose MockValSer from public function
  File "F:\Temp\bot\testbot\.venv\lib\site-packages\pydantic\type_adapter.py", line 144, in wrapped
    return func(self, *args, **kwargs)
  File "F:\Temp\bot\testbot\.venv\lib\site-packages\pydantic\type_adapter.py", line 299, in _init_core_attrs
    self._core_schema.rebuild()
  File "F:\Temp\bot\testbot\.venv\lib\site-packages\pydantic\_internal\_mock_val_ser.py", line 66, in rebuild
    raise PydanticUserError(self._error_message, code=self._code)
pydantic.errors.PydanticUserError: `Config` is not fully defined; you should define `util`, then call `Config.model_rebuild()`.

For further information visit https://errors.pydantic.dev/2.9/u/class-not-fully-defined
```

使用之前的 `pydantic` 版本没问题

**Comment by ProgramRipper** [comment]
pydantic/pydantic#10336
