### ISSUE TITLE
【求助】连接已有数据库时发生错误

### ISSUE THREAD

**Issue by F1Justin** [nonebot/plugin-orm#21]
我之前运行bot和数据库的计算机的系统发生了错误，不得已重装系统。当我恢复好数据库，重新安装好nonebot并尝试连接时发生了如下错误：
```
11-03 11:03:27 [ERROR] uvicorn | Traceback (most recent call last):
  File "/home/justin/lily/.venv/lib/python3.11/site-packages/alembic/script/base.py", line 254, in _catch_revision_errors
    yield
  File "/home/justin/lily/.venv/lib/python3.11/site-packages/alembic/script/base.py", line 317, in get_revisions
    self.revision_map.get_revisions(id_),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/justin/lily/.venv/lib/python3.11/site-packages/alembic/script/revision.py", line 542, in get_revisions
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/justin/lily/.venv/lib/python3.11/site-packages/alembic/script/revision.py", line 542, in <listcomp>
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/justin/lily/.venv/lib/python3.11/site-packages/alembic/script/revision.py", line 565, in get_revisions
    return tuple(
           ^^^^^^
  File "/home/justin/lily/.venv/lib/python3.11/site-packages/alembic/script/revision.py", line 566, in <genexpr>
    self._revision_for_ident(rev_id, branch_label)
  File "/home/justin/lily/.venv/lib/python3.11/site-packages/alembic/script/revision.py", line 637, in _revision_for_ident
    raise ResolutionError(
alembic.script.revision.ResolutionError: No such revision or branch 'ade8cdca5470'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/justin/lily/.venv/lib/python3.11/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.11/contextlib.py", line 204, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/justin/lily/.venv/lib/python3.11/site-packages/nonebot/drivers/fastapi.py", line 155, in _lifespan_manager
    await self._lifespan.startup()
  File "/home/justin/lily/.venv/lib/python3.11/site-packages/nonebot/internal/driver/_lifespan.py", line 66, in startup
    await self._run_lifespan_func(self._startup_funcs)
  File "/home/justin/lily/.venv/lib/python3.11/site-packages/nonebot/internal/driver/_lifespan.py", line 55, in _run_lifespan_func
    await cast(ASYNC_LIFESPAN_FUNC, func)()
  File "/home/justin/lily/.venv/lib/python3.11/site-packages/nonebot_plugin_orm/__init__.py", line 84, in init_orm
    await greenlet_spawn(migrate.check, alembic_config)
  File "/home/justin/lily/.venv/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 201, in greenlet_spawn
    result = context.throw(*sys.exc_info())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/justin/lily/.venv/lib/python3.11/site-packages/nonebot_plugin_orm/migrate.py", line 567, in check
    script.run_env()
  File "/home/justin/lily/.venv/lib/python3.11/site-packages/alembic/script/base.py", line 586, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/home/justin/lily/.venv/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/justin/lily/.venv/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/justin/lily/.venv/lib/python3.11/site-packages/nonebot_plugin_orm/templates/generic/env.py", line 90, in <module>
    await_only(coro)
  File "/home/justin/lily/.venv/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/justin/lily/.venv/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "/home/justin/lily/.venv/lib/python3.11/site-packages/nonebot_plugin_orm/templates/generic/env.py", line 79, in run_migrations_online
    await connection.run_sync(do_run_migrations)
  File "/home/justin/lily/.venv/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/engine.py", line 886, in run_sync
    return await greenlet_spawn(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/justin/lily/.venv/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 203, in greenlet_spawn
    result = context.switch(value)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/justin/lily/.venv/lib/python3.11/site-packages/nonebot_plugin_orm/templates/generic/env.py", line 69, in do_run_migrations
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/home/justin/lily/.venv/lib/python3.11/site-packages/alembic/runtime/environment.py", line 946, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/home/justin/lily/.venv/lib/python3.11/site-packages/alembic/runtime/migration.py", line 616, in run_migrations
    for step in self._migrations_fn(heads, self):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/justin/lily/.venv/lib/python3.11/site-packages/nonebot_plugin_orm/migrate.py", line 552, in retrieve_migrations
    if set(script.get_revisions(rev)) != set(script.get_revisions("heads")):
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/justin/lily/.venv/lib/python3.11/site-packages/alembic/script/base.py", line 314, in get_revisions
    with self._catch_revision_errors():
  File "/usr/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/justin/lily/.venv/lib/python3.11/site-packages/alembic/script/base.py", line 286, in _catch_revision_errors
    raise util.CommandError(resolution) from re
alembic.util.exc.CommandError: Can't locate revision identified by 'ade8cdca5470'

11-03 11:03:27 [ERROR] uvicorn | Application startup failed. Exiting.
```

请问是否有办法连接到已有数据库而不是使用新库？

**Comment by F1Justin** [comment]
已解决
